stages:
    - test
    - bump_version
    - release
    - release_deploy
    - release_notify

variables:
    TRELLIS_GIT_POST: https://trellis.getto.systems/git/post/1.5.2
    TRELLIS_CI_BUMP_VERSION: https://trellis.getto.systems/ci/bump-version/1.15.0
    TRELLIS_PSYCHER_GETTO: https://trellis.getto.systems/psycher/getto/2.7.2

test:
    stage: test
    only:
        refs:
            - schedules

    image: node:latest

    before_script:
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        - . "$HOME/.cargo/env"
        - npm ci
    script:
        - npm test

bump_version:
    stage: bump_version
    only:
        refs:
            - triggers
        variables:
            - $RELEASE

    image: node:latest

    variables:
        BUMP_SCRIPT: "scripts/bump-version.sh"

    before_script:
        - git config user.email admin@getto.systems
        - git config user.name getto
        - curl $TRELLIS_GIT_POST/setup.sh | sh -s -- ./vendor/getto-systems
        - export PATH=$PATH:./vendor/getto-systems/git-post/bin
    script:
        - curl $TRELLIS_CI_BUMP_VERSION/bump_version.sh | bash
        - curl $TRELLIS_CI_BUMP_VERSION/request.sh | bash -s -- ./scripts/bump-message.sh

release:
    stage: release
    only:
        refs:
            - release@getto-systems-base/projects/key-tuner
        changes:
            - .release-version
    except:
        refs:
            - triggers
            - schedules

    image: buildpack-deps:latest

    variables:
        BUMP_MAINT_REPO_FILE: "scripts/bump-maint-repo.txt"

    script:
        - curl $TRELLIS_CI_BUMP_VERSION/push_tags.sh | sh

release_deploy:
    stage: release_deploy
    rules:
        - if: $CI_COMMIT_REF_NAME = release@getto-systems-base/projects/key-tuner
          changes:
              - .release-version
    except:
        refs:
            - triggers
            - schedules
    when: on_success

    image: node:latest

    # Add the following environment variables in CI/CD configuration
    # AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    # AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    # AWS_DEFAULT_REGION: "ap-northeast-1"
    # S3_BUCKET: "key-tuner.getto.systems"

    before_script:
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        - . "$HOME/.cargo/env"
        - apt-get update && apt-get install -y awscli
    script:
        - ./scripts/deploy.sh

release_deploy_public:
    stage: release_deploy
    rules:
        - if: $CI_COMMIT_REF_NAME = release@getto-systems-base/projects/key-tuner
          changes:
              - .release-version
              - web/public/**/*
    except:
        refs:
            - triggers
            - schedules
    when: on_success

    image: debian:latest

    # Add the following environment variables in CI/CD configuration
    # AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    # AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    # AWS_DEFAULT_REGION: "ap-northeast-1"
    # S3_BUCKET: "key-tuner.getto.systems"

    before_script:
        - apt-get update && apt-get install -y awscli
    script:
        - ./scripts/deploy-public.sh

release_success:
    stage: release_notify
    only:
        refs:
            - release@getto-systems-base/projects/key-tuner
        changes:
            - .release-version
    except:
        refs:
            - triggers
            - schedules
    when: on_success

    image: buildpack-deps:latest

    before_script:
        - export url=$GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true
        - export channel=$SLACK_CHANNEL
        - export version=$(cat .release-version)
    script:
        - curl $TRELLIS_PSYCHER_GETTO/notify-release-success.sh | sh -s -- $url $channel $version

release_failure:
    stage: release_notify
    only:
        refs:
            - release@getto-systems-base/projects/key-tuner
        changes:
            - .release-version
    except:
        refs:
            - triggers
            - schedules
    when: on_failure

    image: buildpack-deps:latest

    before_script:
        - export url=$GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true
        - export channel=$SLACK_CHANNEL
        - export version=$(cat .release-version)
    script:
        - curl $TRELLIS_PSYCHER_GETTO/notify-release-failure.sh | sh -s -- $url $channel $version
