stages:
    - test

test:
    stage: test
    only:
        refs:
            - schedules

    image: node:latest

    before_script:
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        - . "$HOME/.cargo/env"
        - npm ci
    script:
        - npm test
